### ISSUE TITLE
Pulsar maintenance: Resolve bigDecimal warining problem

### ISSUE THREAD

**Issue by twang15** [StanfordBioinformatics/pulsar_lims#238]
### Warning message when pushing to Heroku
remote: /tmp/build_cc6e0ce5/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

**Comment by twang15** [comment]
Find and try out a solution here: https://github.com/rails/rails/issues/35144, but it does not work out.

          gem 'bigdecimal', '1.3.5'

remote:
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     NoMethodError: undefined method `new' for BigDecimal:Class
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/configuration.rb:2:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/configuration.rb:2:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:2:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:2:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine.rb:1:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine.rb:1:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:7:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:7:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `require'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/config/application.rb:3:in `require'
remote:  !     /tmp/build_b24832cd/config/application.rb:3:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/Rakefile:4:in `require'
remote:  !     /tmp/build_b24832cd/Rakefile:4:in `<top (required)>'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
remote:  !     /tmp/build_b24832cd/bin/rake:4:in `<main>'


remote:  !
remote: /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: NoMethodError: undefined method `new' for BigDecimal:Class
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/configuration.rb:2:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/configuration.rb:2:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:2:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:2:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine.rb:1:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine.rb:1:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:7:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:7:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `require'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `<top (required)>'
remote: /tmp/build_b24832cd/config/application.rb:3:in `require'
remote: /tmp/build_b24832cd/config/application.rb:3:in `<top (required)>'
remote: /tmp/build_b24832cd/Rakefile:4:in `require'
remote: /tmp/build_b24832cd/Rakefile:4:in `<top (required)>'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
remote: /tmp/build_b24832cd/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
remote: /tmp/build_b24832cd/bin/rake:4:in `<main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1030:in `rake'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:78:in `block (2 levels) in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:72:in `block in run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:71:in `run_assets_precompile_rake_task'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:112:in `block (2 levels) in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1051:in `allow_git'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:105:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:91:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:62:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:60:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:42:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:41:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:35:in `block in compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:34:in `compile'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `block in trace'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `trace'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:15:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to staging-pulsar-encode.
remote:
To https://git.heroku.com/staging-pulsar-encode.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/staging-pulsar-encode.git'

**Comment by twang15** [comment]
Decide not to fix this for our current release

ruby 2.6.7
rails 4.2.1
bundler 1.17.3
