### ISSUE TITLE
Pulsar maintenance: deprecated jbuilder

### ISSUE THREAD

**Issue by twang15** [StanfordBioinformatics/pulsar_lims#239]
### Warning message
remote: Deprecation warning: Expected string default value for '--jbuilder'; got true (boolean).
remote: This will be rejected in the future unless you explicitly pass the options check_default_type: false or call allow_incompatible_default_type! in your code

**Comment by twang15** [comment]
Downgrade Thor to 0.19.2 does not help

[Rails 5.0.0.1 and Ruby 2.3.1., On both of apps I changed the thor gem gem 'thor', '0.19.1'. I then went on to run bundle update, and create the DB.](https://www.javaer101.com/en/article/15863388.html)

The solution does not apply to ruby 2.6.7 and Rail 4.2.1 for us.
**We may need to upgrade rails.**

remote:        rake aborted!
remote:        ArgumentError: An option's default must match its type.
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/parser/option.rb:113:in `validate!'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/parser/argument.rb:24:in `initialize'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/parser/option.rb:9:in `initialize'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `new'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `build_option'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/thor-0.19.2/lib/thor/base.rb:278:in `class_option'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/generators/base.rb:202:in `class_option'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/generators/base.rb:178:in `block in hook_for'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/generators/base.rb:168:in `each'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/generators/base.rb:168:in `hook_for'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/jbuilder-1.5.3/lib/generators/rails/scaffold_controller_generator.rb:9:in `<class:ScaffoldControllerGenerator>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/jbuilder-1.5.3/lib/generators/rails/scaffold_controller_generator.rb:6:in `<module:Generators>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/jbuilder-1.5.3/lib/generators/rails/scaffold_controller_generator.rb:5:in `<module:Rails>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/jbuilder-1.5.3/lib/generators/rails/scaffold_controller_generator.rb:4:in `<top (required)>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/jbuilder-1.5.3/lib/jbuilder/railtie.rb:8:in `block in <class:Railtie>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:228:in `block in run_generators_blocks'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:245:in `each'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:245:in `each_registered_block'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:228:in `run_generators_blocks'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:462:in `block in run_generators_blocks'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine/railties.rb:13:in `each'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine/railties.rb:13:in `each'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:462:in `run_generators_blocks'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/engine.rb:461:in `load_generators'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.9.8/lib/active_model/serializer/railtie.rb:4:in `block in <class:Railtie>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `public_send'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `method_missing'
remote:        /tmp/build_4dc47c42/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_4dc47c42/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
